version: '3.8'

services:
  tf-notebook:
    image: tensorflow/tensorflow:latest-jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/tf/notebooks
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command:
      - jupyter
      - notebook
      - "--NotebookApp.notebook_dir=/tf/notebooks"
      - "--ip=0.0.0.0"
      - "--no-browser"
      - "--allow-root"
