version: "3.8"

services:
  mongo1:
    image: mongo:latest
    hostname: mongo1
    container_name: mongo1
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_REPLICA_SET=rs0
    volumes:
      - mongo1_data:/data/db
    networks:
      - mongo_cluster
    ports:
      - 27017:27017

  mongo2:
    image: mongo:latest
    hostname: mongo2
    container_name: mongo2
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_REPLICA_SET=rs0
    volumes:
      - mongo2_data:/data/db
    networks:
      - mongo_cluster

  mongo3:
    image: mongo:latest
    hostname: mongo3
    container_name: mongo3
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_REPLICA_SET=rs0
    volumes:
      - mongo3_data:/data/db
    networks:
      - mongo_cluster

networks:
  mongo_cluster:

volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data:
