version: "3.8"

services:
  mongo1:
    build: ./mongo
    hostname: mongo1
    container_name: mongo1
    command: mongod --replSet rs0 --bind_ip_all --keyFile /etc/mongo-keyfile --auth
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo1_data:/data/db
    networks:
      - mongo_cluster
    ports:
      - 27017:27017

  mongo2:
    build: ./mongo
    hostname: mongo2
    container_name: mongo2
    command: mongod --replSet rs0 --bind_ip_all --keyFile /etc/mongo-keyfile --auth
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo2_data:/data/db
    networks:
      - mongo_cluster

  mongo3:
    build: ./mongo
    hostname: mongo3
    container_name: mongo3
    command: mongod --replSet rs0 --bind_ip_all --keyFile /etc/mongo-keyfile --auth
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo3_data:/data/db
    networks:
      - mongo_cluster

networks:
  mongo_cluster:

volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data:
