version: '3.8'

services:
  tf-notebook:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/root/notebooks
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command:
      - jupyter
      - lab
      - "--ip=0.0.0.0"
      - "--notebook-dir=/root/notebooks"
      - "--no-browser"
      - "--allow-root"
