version: "3.8"

services:
  tf-notebook:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/root/notebooks
    environment:
      - JUPYTER_ENABLE_LAB=yes
    restart: always
