version: "3.1"

services:
  appwrite:
    image: appwrite/appwrite:latest
    container_name: appwrite
    ports:
      - 80:80
      - 443:443
    environment:
      _APP_ENV: development
      _APP_DOMAIN: localhost
      _APP_DOMAIN_TARGET: localhost
      _APP_STORAGE_LIMIT: 1000000
      _APP_FUNCTIONS_TIMEOUT: 900
      _APP_DB_HOST: ${MONGO_HOST}
      _APP_DB_USER: ${MONGO_INITDB_ROOT_USERNAME}
      _APP_DB_PASS: ${MONGO_INITDB_ROOT_PASSWORD}
      _APP_DB_NAME: ${MONGO_DB}
    volumes:
      - appwrite_storage:/storage
      - appwrite_cache:/cache
    restart: unless-stopped

volumes:
  appwrite_storage:
  appwrite_cache:
