version: "3.8"

services:
  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
    restart: always

  appwrite:
    image: appwrite/appwrite:latest
    depends_on:
      - mongo
    environment:
      - _APP_DB_HOST=${MONGO_HOST}
      - _APP_DB_PORT=27017
      - _APP_DB_USER=${MONGO_INITDB_ROOT_USERNAME}
      - _APP_DB_PASS=${MONGO_INITDB_ROOT_PASSWORD}
      - _APP_DB_SCHEMA=${MONGO_DB}
      - _APP_DB_CLUSTER=enabled
      - _APP_ENV=production
    ports:
      - 80:80
      - 443:443
    volumes:
      - appwrite_data:/storage
    restart: always

volumes:
  mongo_data:
  appwrite_data:
