version: '3.7'

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    container_name: namenode
    ports:
      - "50070:50070"
      - "9000:9000"
    networks:
      - hadoop-net
    volumes:
      - namenode-data:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_namenode_http_address=0.0.0.0:50070
      - HDFS_CONF_dfs_namenode_name_dir=file:///hadoop/dfs/name
      - HDFS_CONF_dfs_permissions_enabled=false

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    container_name: datanode
    ports:
      - "9864:9864"
    networks:
      - hadoop-net
    volumes:
      - datanode-data:/hadoop/dfs/data
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_datanode_data_dir=file:///hadoop/dfs/data
      - HDFS_CONF_dfs_permissions_enabled=false

  spark-master:
    image: bde2020/spark-master:2.4.0-hadoop2.7
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - hadoop-net
    environment:
      - SPARK_MODE=master
      - HADOOP_CONF_DIR=/hadoop/etc/hadoop

  spark-worker:
    image: bde2020/spark-worker:2.4.0-hadoop2.7
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
      - HADOOP_CONF_DIR=/hadoop/etc/hadoop
    depends_on:
      - spark-master
    networks:
      - hadoop-net

  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-server
    ports:
      - "10000:10000"
    networks:
      - hadoop-net
    environment:
      - HIVE_SITE_conf_hive_metastore_uris=thrift://hive-metastore:9083
      - SERVICE_PRECONDITION=hive-metastore:9083
    depends_on:
      - hive-metastore

  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-metastore
    environment:
      - HIVE_SITE_conf_hive_metastore_warehouse_dir=/hive/warehouse
      - HIVE_SITE_conf_hive_metastore_uris=thrift://hive-metastore:9083
      - HIVE_SITE_conf_fs_defaultFS=hdfs://namenode:9000
      - POSTGRES_DB=metastore
      - POSTGRES_USER=hive
      - POSTGRES_PASSWORD=hive
    ports:
      - "9083:9083"
    networks:
      - hadoop-net

networks:
  hadoop-net:
    driver: bridge

volumes:
  namenode-data:
  datanode-data:
